<?php

namespace ContainerEwI1OSd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VYQUVyqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vYQUVyq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vYQUVyq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\AutomationRepository', 'getAutomationRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\AutomationRepository',
        ]);
    }
}
