<?php

namespace Container0TWv6Zs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewsRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\NewsRepository' shared autowired service.
     *
     * @return \App\Repository\NewsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/NewsRepository.php';

        return $container->privates['App\\Repository\\NewsRepository'] = new \App\Repository\NewsRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
