<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IjSMI2VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ijSMI2V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ijSMI2V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'starRep' => ['privates', '.errored..service_locator.ijSMI2V.App\\Entity\\StarRep', NULL, 'Cannot autowire service ".service_locator.ijSMI2V": it needs an instance of "App\\Entity\\StarRep" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'starRep' => 'App\\Entity\\StarRep',
        ]);
    }
}
