<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zcwd2CJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zcwd2CJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zcwd2CJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loan' => ['privates', '.errored..service_locator.Zcwd2CJ.App\\Entity\\Loan', NULL, 'Cannot autowire service ".service_locator.Zcwd2CJ": it needs an instance of "App\\Entity\\Loan" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\BidRepository', 'getBidRepositoryService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'loan' => 'App\\Entity\\Loan',
            'repo' => 'App\\Repository\\BidRepository',
            'security' => '?',
        ]);
    }
}
