<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WQ7ZuWeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WQ7ZuWe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WQ7ZuWe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recResponseRepository' => ['privates', 'App\\Repository\\RecResponseRepository', 'getRecResponseRepositoryService', true],
        ], [
            'entityManager' => '?',
            'recResponseRepository' => 'App\\Repository\\RecResponseRepository',
        ]);
    }
}
