<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1l7AxvuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1l7Axvu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1l7Axvu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recrepo' => ['privates', 'App\\Repository\\InvestissementRepository', 'getInvestissementRepositoryService', true],
        ], [
            'recrepo' => 'App\\Repository\\InvestissementRepository',
        ]);
    }
}
