<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_71PqivqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.71Pqivq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.71Pqivq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'starRepRepository' => ['privates', 'App\\Repository\\StarRepRepository', 'getStarRepRepositoryService', true],
        ], [
            'starRepRepository' => 'App\\Repository\\StarRepRepository',
        ]);
    }
}
