<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualiteRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ActualiteRepository' shared autowired service.
     *
     * @return \App\Repository\ActualiteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ActualiteRepository.php';

        return $container->privates['App\\Repository\\ActualiteRepository'] = new \App\Repository\ActualiteRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
