<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecResponseTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\RecResponseType' shared autowired service.
     *
     * @return \App\Form\RecResponseType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/RecResponseType.php';

        return $container->privates['App\\Form\\RecResponseType'] = new \App\Form\RecResponseType();
    }
}
