<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStarRep2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ijSMI2V.App\Entity\StarRep' shared service.
     *
     * @return \App\Entity\StarRep
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ijSMI2V": it needs an instance of "App\\Entity\\StarRep" but this type has been excluded in "config/services.yaml".');
    }
}
