<?php

namespace ContainerUdl5C0h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8h24xx5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8h24xx5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8h24xx5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recResponseRepository' => ['privates', 'App\\Repository\\RecResponseRepository', 'getRecResponseRepositoryService', true],
        ], [
            'recResponseRepository' => 'App\\Repository\\RecResponseRepository',
        ]);
    }
}
