<?php

namespace ContainerFpKmXnN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBid2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.w9_6ZZP.App\Entity\Bid' shared service.
     *
     * @return \App\Entity\Bid
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.w9_6ZZP": it needs an instance of "App\\Entity\\Bid" but this type has been excluded in "config/services.yaml".');
    }
}
