<?php

namespace ContainerFpKmXnN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLendingReportControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\LendingReportController' shared autowired service.
     *
     * @return \App\Controller\LendingReportController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'LendingReportController.php';

        $container->services['App\\Controller\\LendingReportController'] = $instance = new \App\Controller\LendingReportController(($container->privates['App\\Repository\\AutomationRepository'] ?? $container->load('getAutomationRepositoryService')), ($container->privates['App\\Repository\\LoanRepository'] ?? $container->load('getLoanRepositoryService')), ($container->privates['App\\Repository\\BidRepository'] ?? self::getBidRepositoryService($container)), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\LendingReportController', $container));

        return $instance;
    }
}
