# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        user_avatar:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\OrignameNamer # Optional: Use original file name as file name
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true