<?php

namespace ContainerF2jcSTv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SnrxfMWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SnrxfMW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SnrxfMW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AutomationController::new1' => ['privates', '.service_locator.8Xaq0c0', 'get_ServiceLocator_8Xaq0c0Service', true],
            'App\\Controller\\BidController::approve' => ['privates', '.service_locator.a6fQVqZ', 'get_ServiceLocator_A6fQVqZService', true],
            'App\\Controller\\BidController::delete' => ['privates', '.service_locator.w9_6ZZP', 'get_ServiceLocator_W96ZZPService', true],
            'App\\Controller\\BidController::index' => ['privates', '.service_locator.8Xaq0c0', 'get_ServiceLocator_8Xaq0c0Service', true],
            'App\\Controller\\BidController::new' => ['privates', '.service_locator.bLofnxd', 'get_ServiceLocator_BLofnxdService', true],
            'App\\Controller\\BidController::reject' => ['privates', '.service_locator.w9_6ZZP', 'get_ServiceLocator_W96ZZPService', true],
            'App\\Controller\\LoansController::adminList' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController::adminStats' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController::delete' => ['privates', '.service_locator.119gtIa', 'get_ServiceLocator_119gtIaService', true],
            'App\\Controller\\LoansController::list' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController::myLoans' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController::new' => ['privates', '.service_locator.b_SENms', 'get_ServiceLocator_BSENmsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AutomationController:new1' => ['privates', '.service_locator.8Xaq0c0', 'get_ServiceLocator_8Xaq0c0Service', true],
            'App\\Controller\\BidController:approve' => ['privates', '.service_locator.a6fQVqZ', 'get_ServiceLocator_A6fQVqZService', true],
            'App\\Controller\\BidController:delete' => ['privates', '.service_locator.w9_6ZZP', 'get_ServiceLocator_W96ZZPService', true],
            'App\\Controller\\BidController:index' => ['privates', '.service_locator.8Xaq0c0', 'get_ServiceLocator_8Xaq0c0Service', true],
            'App\\Controller\\BidController:new' => ['privates', '.service_locator.bLofnxd', 'get_ServiceLocator_BLofnxdService', true],
            'App\\Controller\\BidController:reject' => ['privates', '.service_locator.w9_6ZZP', 'get_ServiceLocator_W96ZZPService', true],
            'App\\Controller\\LoansController:adminList' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController:adminStats' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController:delete' => ['privates', '.service_locator.119gtIa', 'get_ServiceLocator_119gtIaService', true],
            'App\\Controller\\LoansController:list' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController:myLoans' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansController:new' => ['privates', '.service_locator.b_SENms', 'get_ServiceLocator_BSENmsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AutomationController::new1' => '?',
            'App\\Controller\\BidController::approve' => '?',
            'App\\Controller\\BidController::delete' => '?',
            'App\\Controller\\BidController::index' => '?',
            'App\\Controller\\BidController::new' => '?',
            'App\\Controller\\BidController::reject' => '?',
            'App\\Controller\\LoansController::adminList' => '?',
            'App\\Controller\\LoansController::adminStats' => '?',
            'App\\Controller\\LoansController::delete' => '?',
            'App\\Controller\\LoansController::list' => '?',
            'App\\Controller\\LoansController::myLoans' => '?',
            'App\\Controller\\LoansController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AutomationController:new1' => '?',
            'App\\Controller\\BidController:approve' => '?',
            'App\\Controller\\BidController:delete' => '?',
            'App\\Controller\\BidController:index' => '?',
            'App\\Controller\\BidController:new' => '?',
            'App\\Controller\\BidController:reject' => '?',
            'App\\Controller\\LoansController:adminList' => '?',
            'App\\Controller\\LoansController:adminStats' => '?',
            'App\\Controller\\LoansController:delete' => '?',
            'App\\Controller\\LoansController:list' => '?',
            'App\\Controller\\LoansController:myLoans' => '?',
            'App\\Controller\\LoansController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
