<?php

namespace ContainerXMgks0U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A6fQVqZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a6fQVqZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a6fQVqZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bid' => ['privates', '.errored..service_locator.a6fQVqZ.App\\Entity\\Bid', NULL, 'Cannot autowire service ".service_locator.a6fQVqZ": it needs an instance of "App\\Entity\\Bid" but this type has been excluded in "config/services.yaml".'],
            'bidRepo' => ['privates', 'App\\Repository\\BidRepository', 'getBidRepositoryService', true],
            'loanRepo' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
        ], [
            'bid' => 'App\\Entity\\Bid',
            'bidRepo' => 'App\\Repository\\BidRepository',
            'loanRepo' => 'App\\Repository\\LoanRepository',
        ]);
    }
}
