<?php

namespace ContainerUxMMTSV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OoSyeOuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OoSyeOu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OoSyeOu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'log' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'repository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'log' => '?',
            'repository' => 'App\\Repository\\LoanRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
