<?php

namespace ContainerKxQ8U7a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BSENmsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b_SENms' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b_SENms'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loanRepo' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
        ], [
            'loanRepo' => 'App\\Repository\\LoanRepository',
        ]);
    }
}
