<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUy6xqV3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUy6xqV3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUy6xqV3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUy6xqV3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUy6xqV3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uy6xqV3',
    'container.build_id' => '8cb7f20b',
    'container.build_time' => 1715636550,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUy6xqV3');
