<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reclamation extends \App\Entity\Reclamation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null],
        "\0".parent::class."\0".'Sujet' => [parent::class, 'Sujet', null],
        "\0".parent::class."\0".'dt' => [parent::class, 'dt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'recResponse' => [parent::class, 'recResponse', null],
        "\0".parent::class."\0".'verified' => [parent::class, 'verified', null],
        'Description' => [parent::class, 'Description', null],
        'Sujet' => [parent::class, 'Sujet', null],
        'dt' => [parent::class, 'dt', null],
        'id' => [parent::class, 'id', null],
        'recResponse' => [parent::class, 'recResponse', null],
        'verified' => [parent::class, 'verified', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
