<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUdl5C0h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUdl5C0h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUdl5C0h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUdl5C0h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUdl5C0h\App_KernelDevDebugContainer([
    'container.build_hash' => 'Udl5C0h',
    'container.build_id' => '8ac1a6f4',
    'container.build_time' => 1708814851,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUdl5C0h');
