<?php

namespace ContainerCY8T7sh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutomationRuleRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AutomationRuleRepository' shared autowired service.
     *
     * @return \App\Repository\AutomationRuleRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/AutomationRuleRepository.php';

        return $container->privates['App\\Repository\\AutomationRuleRepository'] = new \App\Repository\AutomationRuleRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
