<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Loan extends \App\Entity\Loan implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null],
        "\0".parent::class."\0".'bids' => [parent::class, 'bids', null],
        "\0".parent::class."\0".'borrower' => [parent::class, 'borrower', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'interest' => [parent::class, 'interest', null],
        "\0".parent::class."\0".'purpose' => [parent::class, 'purpose', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'term' => [parent::class, 'term', null],
        'amount' => [parent::class, 'amount', null],
        'bids' => [parent::class, 'bids', null],
        'borrower' => [parent::class, 'borrower', null],
        'id' => [parent::class, 'id', null],
        'interest' => [parent::class, 'interest', null],
        'purpose' => [parent::class, 'purpose', null],
        'status' => [parent::class, 'status', null],
        'term' => [parent::class, 'term', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
