<?php

namespace ContainerTXjeNEq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_41YVhw0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.41YVhw0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.41YVhw0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'repository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
        ], [
            'logger' => '?',
            'repository' => 'App\\Repository\\LoanRepository',
        ]);
    }
}
