<?php

namespace ContainerRwsMtxL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BLofnxdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bLofnxd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bLofnxd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loan' => ['privates', '.errored..service_locator.bLofnxd.App\\Entity\\Loan', NULL, 'Cannot autowire service ".service_locator.bLofnxd": it needs an instance of "App\\Entity\\Loan" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\BidRepository', 'getBidRepositoryService', false],
        ], [
            'loan' => 'App\\Entity\\Loan',
            'repo' => 'App\\Repository\\BidRepository',
        ]);
    }
}
