<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZfwS4tlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZfwS4tl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZfwS4tl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commentaire' => ['privates', '.errored..service_locator.ZfwS4tl.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.ZfwS4tl": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
        ]);
    }
}
