<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ULqwtK8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uLqwtK8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uLqwtK8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'qrcodeService' => ['privates', 'App\\Service\\QrCodeService', NULL, 'Cannot autowire service "App\\Service\\QrCodeService": argument "$builder" of method "__construct()" has type "Endroid\\QrCode\\Builder\\BuilderInterface" but this class was not found.'],
            'repository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'qrcodeService' => 'App\\Service\\QrCodeService',
            'repository' => 'App\\Repository\\ReclamationRepository',
            'router' => '?',
        ]);
    }
}
