<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WznTiNpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WznTiNp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WznTiNp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recResponse' => ['privates', '.errored..service_locator.WznTiNp.App\\Entity\\RecResponse', NULL, 'Cannot autowire service ".service_locator.WznTiNp": it needs an instance of "App\\Entity\\RecResponse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'recResponse' => 'App\\Entity\\RecResponse',
        ]);
    }
}
