<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YZ6tzZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y_z6tzZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y_z6tzZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actualiteRepository' => ['privates', 'App\\Repository\\ActualiteRepository', 'getActualiteRepositoryService', true],
        ], [
            'actualiteRepository' => 'App\\Repository\\ActualiteRepository',
        ]);
    }
}
