<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QzQHuoTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qzQHuoT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qzQHuoT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actualite' => ['privates', '.errored..service_locator.qzQHuoT.App\\Entity\\Actualite', NULL, 'Cannot autowire service ".service_locator.qzQHuoT": it needs an instance of "App\\Entity\\Actualite" but this type has been excluded in "config/services.yaml".'],
            'rep' => ['privates', 'App\\Repository\\LikenewsRepository', 'getLikenewsRepositoryService', true],
        ], [
            'actualite' => 'App\\Entity\\Actualite',
            'rep' => 'App\\Repository\\LikenewsRepository',
        ]);
    }
}
