<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActualiteTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ActualiteType' shared autowired service.
     *
     * @return \App\Form\ActualiteType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ActualiteType.php';

        return $container->privates['App\\Form\\ActualiteType'] = new \App\Form\ActualiteType();
    }
}
