<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvestissementControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\InvestissementController' shared autowired service.
     *
     * @return \App\Controller\InvestissementController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InvestissementController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/TwilioClient.php';

        $container->services['App\\Controller\\InvestissementController'] = $instance = new \App\Controller\InvestissementController(new \App\Service\TwilioClient($container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN'), $container->getEnv('TWILIO_PHONE_NUMBER')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\InvestissementController', $container));

        return $instance;
    }
}
