<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQrCodeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QrCodeService' shared autowired service.
     *
     * @return \App\Service\QrCodeService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\QrCodeService": argument "$builder" of method "__construct()" has type "Endroid\\QrCode\\Builder\\BuilderInterface" but this class was not found.');
    }
}
