<?php

namespace ContainerUy6xqV3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecResponseRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\RecResponseRepository' shared autowired service.
     *
     * @return \App\Repository\RecResponseRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/RecResponseRepository.php';

        return $container->privates['App\\Repository\\RecResponseRepository'] = new \App\Repository\RecResponseRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
