<?php

namespace Container8OqGckb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutomationRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\AutomationRepository' shared autowired service.
     *
     * @return \App\Repository\AutomationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/AutomationRepository.php';

        return $container->privates['App\\Repository\\AutomationRepository'] = new \App\Repository\AutomationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
