<?php

namespace ContainerVJZOkDL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_119gtIaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.119gtIa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.119gtIa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loan' => ['privates', '.errored..service_locator.119gtIa.App\\Entity\\Loan', NULL, 'Cannot autowire service ".service_locator.119gtIa": it needs an instance of "App\\Entity\\Loan" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
        ], [
            'loan' => 'App\\Entity\\Loan',
            'repository' => 'App\\Repository\\LoanRepository',
        ]);
    }
}
