<?php

namespace ContainerVJZOkDL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TC_WhAuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TC.WhAu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TC.WhAu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'automation' => ['privates', '.errored..service_locator.TC.WhAu.App\\Entity\\Automation', NULL, 'Cannot autowire service ".service_locator.TC.WhAu": it needs an instance of "App\\Entity\\Automation" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\AutomationRepository', 'getAutomationRepositoryService', true],
        ], [
            'automation' => 'App\\Entity\\Automation',
            'repo' => 'App\\Repository\\AutomationRepository',
        ]);
    }
}
