# config/routes.yaml
admin_index:
    path: /admin/index.html
    controller: App\Controller\AdminController::index

admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::index
    methods: GET
    options:
        expose: true

afficheall:
    path: /afficheAll
    controller: App\Controller\AdminController::afficher
    methods: GET
    options:
        expose: true

activer_user:
    path: /activer/{id}
    controller: App\Controller\AdminController::activerUser
    methods: [GET, POST]
    options:
        expose: true

desactiver_user:
    path: /desactiver/{id}
    controller: App\Controller\AdminController::desactiverUser
    methods: [GET, POST]
    options:
        expose: true

send_mail_to_user:
    path: /email/{email_use}
    controller: App\Controller\AdminController::sendEmail
    methods: GET|POST
    options:
        expose: true

user_pdf:
    path: /pdf/espace/download
    controller: App\Controller\AdminController::packPdf
    methods: GET
    options:
        expose: true

account:
    path: /account
    controller: App\Controller\AccountController::index
    methods: [GET, POST]
    options:
        expose: true

password_reset:
    path: /reset
    controller: App\Controller\AccountController::editAction
    methods: [GET, POST]
    options:
        expose: true

banned:
    path: /banned
    controller: App\Controller\BannedController::index
    methods: GET
    options:
        expose: true                


app_landing_page:
    path: /pp_landing_page
    controller: App\Controller\LandingPageController::index
    methods: GET
    options:
        expose: true

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]
    options:
        expose: true

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    methods: GET
    options:
        expose: true

register_emp:
    path: /registeremploye
    controller: App\Controller\RegistrationController::registeremp
    methods: [GET, POST]
    options:
        expose: true

app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ResetPasswordController::reset
    methods: [GET, POST]
    options:
        expose: true
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]
    options:
        expose: true

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: GET
    options:
        expose: true

search_users:
    path: /search
    controller: App\Controller\AdminController::search