<?php

<<<<<<<< HEAD:var/cache/dev/ContainerDAmAGcg/get_ServiceLocator_IJyah0vService.php
namespace ContainerDAmAGcg;
========
namespace ContainerC04TK59;
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_OHKisKrService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
<<<<<<<< HEAD:var/cache/dev/ContainerDAmAGcg/get_ServiceLocator_IJyah0vService.php
class get_ServiceLocator_IJyah0vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iJyah0v' shared service.
========
class get_ServiceLocator_OHKisKrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oHKisKr' shared service.
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_OHKisKrService.php
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:var/cache/dev/ContainerDAmAGcg/get_ServiceLocator_IJyah0vService.php
        return $container->privates['.service_locator.iJyah0v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LoansListController::delete' => ['privates', '.service_locator.119gtIa', 'get_ServiceLocator_119gtIaService', true],
            'App\\Controller\\LoansListController::index' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansListController::new' => ['privates', '.service_locator.b_SENms', 'get_ServiceLocator_BSENmsService', true],
========
        return $container->privates['.service_locator.oHKisKr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ListLoansController::index' => ['privates', '.service_locator.2i4KyfS', 'get_ServiceLocator_2i4KyfSService', true],
            'App\\Controller\\ListLoansController::new' => ['privates', '.service_locator.qBvi2AV', 'get_ServiceLocator_QBvi2AVService', true],
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_OHKisKrService.php
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
<<<<<<<< HEAD:var/cache/dev/ContainerDAmAGcg/get_ServiceLocator_IJyah0vService.php
            'App\\Controller\\LoansListController:delete' => ['privates', '.service_locator.119gtIa', 'get_ServiceLocator_119gtIaService', true],
            'App\\Controller\\LoansListController:index' => ['privates', '.service_locator.JmgQ6AO', 'get_ServiceLocator_JmgQ6AOService', true],
            'App\\Controller\\LoansListController:new' => ['privates', '.service_locator.b_SENms', 'get_ServiceLocator_BSENmsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LoansListController::delete' => '?',
            'App\\Controller\\LoansListController::index' => '?',
            'App\\Controller\\LoansListController::new' => '?',
========
            'App\\Controller\\ListLoansController:index' => ['privates', '.service_locator.2i4KyfS', 'get_ServiceLocator_2i4KyfSService', true],
            'App\\Controller\\ListLoansController:new' => ['privates', '.service_locator.qBvi2AV', 'get_ServiceLocator_QBvi2AVService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ListLoansController::index' => '?',
            'App\\Controller\\ListLoansController::new' => '?',
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_OHKisKrService.php
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
<<<<<<<< HEAD:var/cache/dev/ContainerDAmAGcg/get_ServiceLocator_IJyah0vService.php
            'App\\Controller\\LoansListController:delete' => '?',
            'App\\Controller\\LoansListController:index' => '?',
            'App\\Controller\\LoansListController:new' => '?',
========
            'App\\Controller\\ListLoansController:index' => '?',
            'App\\Controller\\ListLoansController:new' => '?',
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_OHKisKrService.php
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
