version: "3.6"
services:
 db:
   image: mysql:latest
   container_name: db
   ports:
     - 3306:3306
   volumes:
     - db_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=root_password
     - MYSQL_USER=user
     - MYSQL_PASSWORD=user_password
     - MYSQL_DATABASE=safe-spot
   restart: always
 
 phpmyadmin:
   depends_on:
     - db
   image: phpmyadmin/phpmyadmin:latest
   container_name: phpmyadmin
   restart: always
   ports:
     - 8180:80
   environment:
     PMA_HOST: db
     MYSQL_ROOT_PASSWORD: root_password
 
volumes:
 db_data:
