<?php

namespace ContainerTrHh6O8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAutomationRuleTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AutomationRuleType' shared autowired service.
     *
     * @return \App\Form\AutomationRuleType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AutomationRuleType.php';

        return $container->privates['App\\Form\\AutomationRuleType'] = new \App\Form\AutomationRuleType();
    }
}
