<?php

namespace ContainerIqV0ZVx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W96ZZPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w9_6ZZP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w9_6ZZP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bid' => ['privates', '.errored..service_locator.w9_6ZZP.App\\Entity\\Bid', NULL, 'Cannot autowire service ".service_locator.w9_6ZZP": it needs an instance of "App\\Entity\\Bid" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\BidRepository', 'getBidRepositoryService', true],
        ], [
            'bid' => 'App\\Entity\\Bid',
            'repo' => 'App\\Repository\\BidRepository',
        ]);
    }
}
