<?php

namespace ContainerIqV0ZVx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Xaq0c0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Xaq0c0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Xaq0c0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\BidRepository', 'getBidRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\BidRepository',
        ]);
    }
}
