<?php

namespace ContainerASiiuQV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoan2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bLofnxd.App\Entity\Loan' shared service.
     *
     * @return \App\Entity\Loan
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bLofnxd": it needs an instance of "App\\Entity\\Loan" but this type has been excluded in "config/services.yaml".');
    }
}
