<?php

<<<<<<<< HEAD:var/cache/dev/ContainerIcbrOko/get_ServiceLocator_119gtIaService.php
namespace ContainerIcbrOko;
========
namespace ContainerC04TK59;
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_2i4KyfSService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
<<<<<<<< HEAD:var/cache/dev/ContainerIcbrOko/get_ServiceLocator_119gtIaService.php
class get_ServiceLocator_119gtIaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.119gtIa' shared service.
========
class get_ServiceLocator_2i4KyfSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2i4KyfS' shared service.
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_2i4KyfSService.php
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
<<<<<<<< HEAD:var/cache/dev/ContainerIcbrOko/get_ServiceLocator_119gtIaService.php
        return $container->privates['.service_locator.119gtIa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loan' => ['privates', '.errored..service_locator.119gtIa.App\\Entity\\Loan', NULL, 'Cannot autowire service ".service_locator.119gtIa": it needs an instance of "App\\Entity\\Loan" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
        ], [
            'loan' => 'App\\Entity\\Loan',
========
        return $container->privates['.service_locator.2i4KyfS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\LoanRepository', 'getLoanRepositoryService', true],
        ], [
>>>>>>>> 9a42ed6 (create loan form):var/cache/dev/ContainerC04TK59/get_ServiceLocator_2i4KyfSService.php
            'repository' => 'App\\Repository\\LoanRepository',
        ]);
    }
}
