<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLr1tzce\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLr1tzce/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLr1tzce.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLr1tzce\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLr1tzce\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lr1tzce',
    'container.build_id' => '5c44d4df',
    'container.build_time' => 1707320644,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLr1tzce');
