<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVmyPuu7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVmyPuu7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVmyPuu7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVmyPuu7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVmyPuu7\App_KernelDevDebugContainer([
    'container.build_hash' => 'VmyPuu7',
    'container.build_id' => '2a3ecba9',
    'container.build_time' => 1708876083,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVmyPuu7');
