<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVJZOkDL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVJZOkDL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVJZOkDL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVJZOkDL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVJZOkDL\App_KernelDevDebugContainer([
    'container.build_hash' => 'VJZOkDL',
    'container.build_id' => '75972215',
    'container.build_time' => 1709396412,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVJZOkDL');
