<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_dons' => [[], ['_controller' => 'App\\Controller\\DonsController::index'], [], [['text', '/dons']], [], [], []],
    'add_Dons' => [[], ['_controller' => 'App\\Controller\\DonsController::Add'], [], [['text', '/add_Dons']], [], [], []],
    'afficher_dons' => [[], ['_controller' => 'App\\Controller\\DonsController::AfficheDons'], [], [['text', '/afficher_dons']], [], [], []],
    'delete_dons' => [['id'], ['_controller' => 'App\\Controller\\DonsController::Delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete_dons']], [], [], []],
    'update_dons' => [['id'], ['_controller' => 'App\\Controller\\DonsController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update_dons']], [], [], []],
    'app_investissement' => [[], ['_controller' => 'App\\Controller\\InvestissementController::index'], [], [['text', '/investissement']], [], [], []],
    'add_investissement' => [[], ['_controller' => 'App\\Controller\\InvestissementController::Add'], [], [['text', '/add_investissement']], [], [], []],
    'afficher_inv' => [[], ['_controller' => 'App\\Controller\\InvestissementController::AfficheInvestissement'], [], [['text', '/afficher_inv']], [], [], []],
    'delete_inv' => [['id'], ['_controller' => 'App\\Controller\\InvestissementController::Delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete_inv']], [], [], []],
    'update_inv' => [['id'], ['_controller' => 'App\\Controller\\InvestissementController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/update_inv']], [], [], []],
    'statsabonn' => [[], ['_controller' => 'App\\Controller\\InvestissementController::statistiques'], [], [['text', '/statsabonn']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'generate_pdf' => [[], ['_controller' => 'App\\Controller\\InvestissementController::generatePdf'], [], [['text', '/generate-pdf']], [], [], []],
];
