<?php

namespace ContainerBiznxx2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JrsnFEwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jrsnFEw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jrsnFEw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exp' => ['privates', '.errored..service_locator.jrsnFEw.App\\Entity\\Exp', NULL, 'Cannot autowire service ".service_locator.jrsnFEw": it needs an instance of "App\\Entity\\Exp" but this type has been excluded in "config/services.yaml".'],
        ], [
            'exp' => 'App\\Entity\\Exp',
        ]);
    }
}
