<?php

namespace ContainerBiznxx2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W4Fk9gJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w4Fk9gJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w4Fk9gJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actualite' => ['privates', '.errored..service_locator.w4Fk9gJ.App\\Entity\\Actualite', NULL, 'Cannot autowire service ".service_locator.w4Fk9gJ": it needs an instance of "App\\Entity\\Actualite" but this type has been excluded in "config/services.yaml".'],
        ], [
            'actualite' => 'App\\Entity\\Actualite',
        ]);
    }
}
