<?php

namespace ContainerBiznxx2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hA5lrtQ.App\Entity\Exp' shared service.
     *
     * @return \App\Entity\Exp
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hA5lrtQ": it needs an instance of "App\\Entity\\Exp" but this type has been excluded in "config/services.yaml".');
    }
}
