<?php

namespace ContainerBiznxx2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecResponse2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.l9lstuz.App\Entity\RecResponse' shared service.
     *
     * @return \App\Entity\RecResponse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.l9lstuz": it needs an instance of "App\\Entity\\RecResponse" but this type has been excluded in "config/services.yaml".');
    }
}
